#!/usr/bin/env bash
set -euo pipefail

echo "Uninstalling dotfiles setup"

# Unstow user-level configs
if command -v stow >/dev/null 2>&1; then
  echo "Removing stow symlinks from home directory..."
  stow -D .
else
  echo "GNU Stow not found; skipping unstow."
fi

# Unstow system-level configs
if [ -d "root-symlinks" ]; then
  echo "Removing system-level symlinks..."
  sudo stow -D -t / root-symlinks || true
fi

# Restore original backed-up files
restore_file() {
  local original="$1"
  local backup="$1.bak"

  if [ -f "$backup" ]; then
    echo "Restoring backup for $original..."
    sudo mv -f "$backup" "$original"
  else
    echo "No backup found for $original; skipping."
  fi
}

echo "Restoring original configuration backups..."
restore_file ~/.bashrc
restore_file /etc/dnf/dnf.conf

# Clean up git config files generated by setup
if [ -d "$HOME/.config/git" ]; then
  echo "Removing local git signing configs..."
  rm -f "$HOME/.config/git/local-config"
  rm -f "$HOME/.config/git/allowed_signers"
fi

echo "Cleanup complete."
echo "Your original configuration has been restored where possible."
