general.import = ["~/.config/alacritty/myTheme.toml"]

live_config_reload = true

[window]
dynamic_title = true
opacity = 0.85
startup_mode = "Maximized"

[selection]
save_to_clipboard = true

[scrolling]
history = 2000

[font]
size = 15.0

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "retina"

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "bold"

[font.italic]
family = "FiraMono"
style = "medium italic"
